title: Structurizr
description: Documentation for the Structurizr tooling.
theme: just-the-docs
color_scheme: structurizr

url: https://docs.structurizr.com

logo: "/images/structurizr-banner-light.png"
favicon_ico: "/images/favicon.png"

nav_external_links:
  - title: playground.structurizr.com
    url: https://playground.structurizr.com
  - title: GitHub
    url: https://github.com/structurizr/structurizr
  - title: Issue tracker
    url: https://github.com/structurizr/structurizr/issues
  - title: Patreon
    url: https://patreon.com/structurizr

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/structurizr/structurizr.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
