title: Structurizr
description: Documentation for the Structurizr tooling.
theme: just-the-docs
color_scheme: structurizr

url: https://docs.structurizr.com

logo: "/assets/images/structurizr-banner.png"
favicon_ico: "/assets/images/favicon.ico"

nav_external_links:
  - title: Playground
    url: https://playground.structurizr.com
  - title: Patreon
    url: https://patreon.com/structurizr

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/structurizr/structurizr.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
